# 1. 前言

工欲善其，事必先利其器。研究设计是临床试验的灵魂，而样本量计算是研究设计的重中之重，但是国内却缺乏这方面较为实用的专著。

其实我们在医学教育阶段就存在这个缺失。作者自己在临床医学本科、硕士及博士阶段都学习了医学统计学，工作后还获得了非全日制流行病与卫生统计学硕士学位，但在临床研究的实践中仍深刻体会到医学统计学的教育与临床研究实践的脱节。这一现象仍然在持续，我们招聘面试的许多临床医学博士，在面对简单的样本量计算时仍然不知所措。

作者加入医药公司从事临床研究方面的工作二十余年，参与了众多的临床研究，包括公司发起的临床试验和研究者发起的研究。我们收到的研究者发起的研究申请，样本量计算常存在一些疏漏甚至明显的错误。有些研究者声称已经请了专业统计师做了计算，但待到三方直接讨论后，往往是医生和统计师之间的沟通出了问题，或者医生提供的参数不是统计师所需要的，或者统计师误解了医生的意图。

显然，需要这样一本面对临床医生/临床研究者的书，除了提高自身的研究设计能力，也可作为桥梁加强临床医生/临床研究者与专业统计师之间的沟通。

本书主要面向临床医生/临床研究者，也可供药械公司医学事务及临床运营的同仁参考。本书强调实用性，并有以下几个特色。一是以案例分析为主，在简单介绍样本量计算方法之后，直接引出实例。这些实例有监管机构指导原则里的案例，更多的是发表在NEJM，Lancet，JAMA等高影响力期刊上的经典研究，重点关注我国学者的成果，同时也包括少量作者直接参与的研究，再现其样本量计算过程，增强读者自行进行样本量计算的信心。第二，样本量计算的实现手段多样。临床研究者很少直接使用SAS等专业软件，我们从Excel入手，将一些常见的样本量计算公式嵌入自制的Excel表中，简便易行。该Excel表已在作者所在公司内部供医学经理已使用数年，颇受欢迎。Excel表可以在网页下载[（）]{.mark}。所有Excel表的样本量计算都经PASS软件（2024版本）验证，本书还提供了PASS软件参数填写的界面供参考。最后，我们精选了一些R语言包，提供模板式的样本量计算代码，可方便套用，不必再将功能强大且免费的R语言视为畏途。第三，样本量计算的适用场景丰富，以随机对照试验为主，也包含了观察性研究；既有常见的两样本均数、率的比较，也有单组目标值、诊断试验、生存分析，还有成组序贯设计及样本量再计算等。

我们在讲解样本量计算的同时，在每章的末尾适当讨论不同的样本量计算方法的比较与选用，并分享我们自己的实战经验以及发表的一些相关的方法学论文，成为本书的又一亮点。

本书的主要目的是使临床医生/临床研究者和相关的非统计专业的研究人员可以自行做一些常见的样本量计算，甚至涉及一些较为复杂的研究设计，比如成组序贯设计与样本量再计算；也为其需要与专业统计师沟通时提供足够的知识储备。同时也希望本书有助于专业统计师从临床的视角去理解临床医生/临床研究者对样本量计算的需求，也即达到本书的桥梁的作用。作者才疏学浅，只为抛砖引玉。Zeng Zhiyu编写了主要内容，Li Qing 编写了诊断试验一章，Liu Qing 提供了部分案例。本书难免存在一些问题，特别是我们在讨论部分的一些见解，我们真诚欢迎您的意见与建议，联系方式：zhiyu.zeng@bsci.com。


[谢谢！]{.mark}

2025.[6]{.mark}
